apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.appName }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
    spec:
      containers:
      - name: {{ .Values.metadata.appName }}
        image: "{{ .Values.image.name}}:{{ .Values.image.tag}}"
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: KEYCLOAK_HOSTNAME
          value: {{ .Values.env.hostname }}
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080