apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.appName }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.appName }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.metadata.appName }}
  type: LoadBalancer